// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdJr6zkREYDjE67URr3R_qaDAf5eYfqhw',
    appId: '1:58177115469:web:313927249abbf6bd5d9304',
    messagingSenderId: '58177115469',
    projectId: 'gamezone-108f6',
    authDomain: 'gamezone-108f6.firebaseapp.com',
    databaseURL: 'https://gamezone-108f6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gamezone-108f6.firebasestorage.app',
    measurementId: 'G-XZWQV50QDS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5-sa_qW139kS6q3yBgdqmmQSQIgoRxr8',
    appId: '1:58177115469:android:49f082b3a26119135d9304',
    messagingSenderId: '58177115469',
    projectId: 'gamezone-108f6',
    databaseURL: 'https://gamezone-108f6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gamezone-108f6.firebasestorage.app',
  );
}
